const fs = require('fs');
let c = fs.readFileSync('src/components/sections/FaqSection.tsx', 'utf8');

c = c.replace(/#f8f9fa/g, '#141414');
c = c.replace(/#00356B/gi, '#ef443b');
c = c.replace(/#86bc25/gi, '#ef443b');
c = c.replace(/bg-gradient-to-br from-white to-\[\#f8f9fa\]/g, 'bg-[#141414]');
c = c.replace(/bg-white/g, 'bg-[#1a1a1a]');
c = c.replace(/bg-gray-50/g, 'bg-[#111]');
c = c.replace(/bg-\[\#e5f0f7\]/gi, 'bg-[#1e1e1e]');
c = c.replace(/bg-\[\#f0f7ea\]/gi, 'bg-[#1e1e1e]');
c = c.replace(/hover:bg-gray-50/g, 'hover:bg-[#222]');
c = c.replace(/hover:bg-gray-100/g, 'hover:bg-[#333]');
c = c.replace(/hover:bg-\[\#e5f0f7\]/gi, 'hover:bg-[#ef443b]\/10');
c = c.replace(/hover:bg-\[\#f0f7ea\]/gi, 'hover:bg-[#ef443b]\/10');
c = c.replace(/border-gray-200/g, 'border-[#333]');
c = c.replace(/border-gray-100/g, 'border-[#222]');
c = c.replace(/ring-gray-200/g, 'ring-[#333]');
c = c.replace(/text-gray-900/g, 'text-white');
c = c.replace(/text-\[\#1a1a1a\]/gi, 'text-white');
c = c.replace(/text-gray-600/g, 'text-[#a0a0a0]');
c = c.replace(/text-gray-500/g, 'text-[#a0a0a0]');
c = c.replace(/text-gray-400/g, 'text-[#707070]');
c = c.replace(/textDark: "#1a1a1a"/g, 'textDark: "#ffffff"');
c = c.replace(/#f1f1f1/g, '#222222');
c = c.replace(/shadow-sm/g, 'shadow-none');
c = c.replace(/shadow-md/g, 'shadow-none');
c = c.replace(/shadow-lg/g, 'shadow-none');
c = c.replace(/shadow-\[.*?\]/g, 'shadow-none');

fs.writeFileSync('src/components/sections/FaqSection.tsx', c);
console.log('FAQ section updated.');
